#:schema node_modules/wrangler/config-schema.json
name = "atpcdn"
main = "src/index.ts"
compatibility_date = "2024-12-18"
compatibility_flags = ["nodejs_compat"]

[observability]
enabled = true

[[r2_buckets]]
bucket_name = "atpcdn-dev"
binding = "atpcdn_dev"
